# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: rgb(130,130,130);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame_top = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_top.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalFrame_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalFrame_top.setObjectName("horizontalFrame_top")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_top)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalFrame_top = QtWidgets.QFrame(self.horizontalFrame_top)
        self.verticalFrame_top.setMaximumSize(QtCore.QSize(16777215, 25))
        self.verticalFrame_top.setAutoFillBackground(False)
        self.verticalFrame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_top.setObjectName("verticalFrame_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.verticalFrame_top)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_top = QtWidgets.QLabel(self.verticalFrame_top)
        self.label_top.setMinimumSize(QtCore.QSize(0, 25))
        self.label_top.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_top.setStyleSheet("QLabel {\n"
"    background-color: rgb(150,150,150);\n"
"}")
        self.label_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_top.setText("")
        self.label_top.setObjectName("label_top")
        self.horizontalLayout_5.addWidget(self.label_top)
        self.horizontalLayout_7.addWidget(self.verticalFrame_top)
        self.frame_close = QtWidgets.QFrame(self.horizontalFrame_top)
        self.frame_close.setMinimumSize(QtCore.QSize(25, 25))
        self.frame_close.setMaximumSize(QtCore.QSize(25, 25))
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_min_window = QtWidgets.QPushButton(self.frame_close)
        self.pushButton_min_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_min_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_min_window.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_min_window.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/8666554_minus_square_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_window.setIcon(icon)
        self.pushButton_min_window.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_min_window.setFlat(True)
        self.pushButton_min_window.setObjectName("pushButton_min_window")
        self.horizontalLayout_4.addWidget(self.pushButton_min_window)
        self.horizontalLayout_7.addWidget(self.frame_close)
        self.frame_min = QtWidgets.QFrame(self.horizontalFrame_top)
        self.frame_min.setMinimumSize(QtCore.QSize(25, 25))
        self.frame_min.setMaximumSize(QtCore.QSize(25, 25))
        self.frame_min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_min.setObjectName("frame_min")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_min)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_close_window = QtWidgets.QPushButton(self.frame_min)
        self.pushButton_close_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close_window.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_close_window.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/8666744_x_square_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_window.setIcon(icon1)
        self.pushButton_close_window.setIconSize(QtCore.QSize(30, 20))
        self.pushButton_close_window.setFlat(True)
        self.pushButton_close_window.setObjectName("pushButton_close_window")
        self.horizontalLayout_2.addWidget(self.pushButton_close_window)
        self.horizontalLayout_7.addWidget(self.frame_min)
        self.verticalLayout_2.addWidget(self.horizontalFrame_top)
        self.verticalFrame_bot = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_bot.setObjectName("verticalFrame_bot")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalFrame_bot)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_right = QtWidgets.QFrame(self.verticalFrame_bot)
        self.button_right.setMinimumSize(QtCore.QSize(80, 0))
        self.button_right.setMaximumSize(QtCore.QSize(80, 16777215))
        self.button_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_right.setObjectName("button_right")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.button_right)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.vertical_button_3 = QtWidgets.QFrame(self.button_right)
        self.vertical_button_3.setMinimumSize(QtCore.QSize(80, 0))
        self.vertical_button_3.setMaximumSize(QtCore.QSize(80, 45))
        self.vertical_button_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vertical_button_3.setObjectName("vertical_button_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.vertical_button_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_find_camera = QtWidgets.QPushButton(self.vertical_button_3)
        self.pushButton_find_camera.setMinimumSize(QtCore.QSize(80, 45))
        self.pushButton_find_camera.setMaximumSize(QtCore.QSize(80, 45))
        self.pushButton_find_camera.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_find_camera.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/8666693_search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_find_camera.setIcon(icon2)
        self.pushButton_find_camera.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_find_camera.setDefault(False)
        self.pushButton_find_camera.setFlat(True)
        self.pushButton_find_camera.setObjectName("pushButton_find_camera")
        self.verticalLayout_7.addWidget(self.pushButton_find_camera)
        self.verticalLayout_11.addWidget(self.vertical_button_3)
        self.vertical_button_5 = QtWidgets.QFrame(self.button_right)
        self.vertical_button_5.setMinimumSize(QtCore.QSize(80, 0))
        self.vertical_button_5.setMaximumSize(QtCore.QSize(80, 45))
        self.vertical_button_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vertical_button_5.setObjectName("vertical_button_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.vertical_button_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_add_camera = QtWidgets.QPushButton(self.vertical_button_5)
        self.pushButton_add_camera.setMinimumSize(QtCore.QSize(80, 45))
        self.pushButton_add_camera.setMaximumSize(QtCore.QSize(80, 45))
        self.pushButton_add_camera.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_add_camera.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/8666650_file_plus_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_camera.setIcon(icon3)
        self.pushButton_add_camera.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_add_camera.setFlat(True)
        self.pushButton_add_camera.setObjectName("pushButton_add_camera")
        self.verticalLayout_10.addWidget(self.pushButton_add_camera)
        self.verticalLayout_11.addWidget(self.vertical_button_5)
        self.vertical_button_4 = QtWidgets.QFrame(self.button_right)
        self.vertical_button_4.setMinimumSize(QtCore.QSize(80, 0))
        self.vertical_button_4.setMaximumSize(QtCore.QSize(80, 45))
        self.vertical_button_4.setToolTip("")
        self.vertical_button_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vertical_button_4.setObjectName("vertical_button_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.vertical_button_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_play = QtWidgets.QPushButton(self.vertical_button_4)
        self.pushButton_play.setMinimumSize(QtCore.QSize(80, 45))
        self.pushButton_play.setMaximumSize(QtCore.QSize(80, 45))
        self.pushButton_play.setToolTip("")
        self.pushButton_play.setWhatsThis("")
        self.pushButton_play.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:pressed {\n"
"     border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/8666551_play_circle_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play.setIcon(icon4)
        self.pushButton_play.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_play.setFlat(True)
        self.pushButton_play.setObjectName("pushButton_play")
        self.verticalLayout_8.addWidget(self.pushButton_play)
        self.verticalLayout_11.addWidget(self.vertical_button_4)
        self.vertical_button_1 = QtWidgets.QFrame(self.button_right)
        self.vertical_button_1.setMinimumSize(QtCore.QSize(80, 0))
        self.vertical_button_1.setMaximumSize(QtCore.QSize(80, 45))
        self.vertical_button_1.setToolTip("")
        self.vertical_button_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vertical_button_1.setObjectName("vertical_button_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.vertical_button_1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_login = QtWidgets.QPushButton(self.vertical_button_1)
        self.pushButton_login.setMinimumSize(QtCore.QSize(80, 45))
        self.pushButton_login.setMaximumSize(QtCore.QSize(80, 45))
        self.pushButton_login.setToolTip("")
        self.pushButton_login.setWhatsThis("")
        self.pushButton_login.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:pressed {\n"
"     border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_login.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/8666628_user_check_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon5)
        self.pushButton_login.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_login.setFlat(True)
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_5.addWidget(self.pushButton_login)
        self.verticalLayout_11.addWidget(self.vertical_button_1)
        self.verticalFrame = QtWidgets.QFrame(self.button_right)
        self.verticalFrame.setMaximumSize(QtCore.QSize(80, 20))
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalFrame)
        self.label_4.setMaximumSize(QtCore.QSize(80, 20))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: rgb(150,150,150);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayout_11.addWidget(self.verticalFrame)
        self.vertical_button_2 = QtWidgets.QFrame(self.button_right)
        self.vertical_button_2.setMinimumSize(QtCore.QSize(80, 0))
        self.vertical_button_2.setMaximumSize(QtCore.QSize(80, 45))
        self.vertical_button_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vertical_button_2.setObjectName("vertical_button_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.vertical_button_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_info = QtWidgets.QPushButton(self.vertical_button_2)
        self.pushButton_info.setMinimumSize(QtCore.QSize(80, 45))
        self.pushButton_info.setMaximumSize(QtCore.QSize(80, 45))
        self.pushButton_info.setStyleSheet("QPushButton {\n"
"    background-color: rgb(190,190,190);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 3px solid rgb(85, 165, 127);\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_info.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/8666788_info_information_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_info.setIcon(icon6)
        self.pushButton_info.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_info.setFlat(True)
        self.pushButton_info.setObjectName("pushButton_info")
        self.verticalLayout_6.addWidget(self.pushButton_info)
        self.verticalLayout_11.addWidget(self.vertical_button_2)
        self.verticalFrame1 = QtWidgets.QFrame(self.button_right)
        self.verticalFrame1.setMinimumSize(QtCore.QSize(80, 0))
        self.verticalFrame1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(150,150,150);\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.verticalLayout_11.addWidget(self.verticalFrame1)
        self.horizontalLayout_3.addWidget(self.button_right)
        self.see_frame = QtWidgets.QFrame(self.verticalFrame_bot)
        self.see_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.see_frame.setObjectName("see_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.see_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tb_frame = QtWidgets.QFrame(self.see_frame)
        self.tb_frame.setObjectName("tb_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tb_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_search_camera = QtWidgets.QTableWidget(self.tb_frame)
        self.tableWidget_search_camera.setEnabled(True)
        self.tableWidget_search_camera.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget_search_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_search_camera.setAutoFillBackground(False)
        self.tableWidget_search_camera.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(220,220,220);\n"
"    color: rgb(0,0,0);  \n"
"}\n"
"QTableWidget:pressed {\n"
"    border: 2px solid green;\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"}")
        self.tableWidget_search_camera.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_search_camera.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_search_camera.setWordWrap(False)
        self.tableWidget_search_camera.setCornerButtonEnabled(True)
        self.tableWidget_search_camera.setObjectName("tableWidget_search_camera")
        self.tableWidget_search_camera.setColumnCount(5)
        self.tableWidget_search_camera.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(203, 0, 0, 0))
        self.tableWidget_search_camera.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(4, item)
        self.tableWidget_search_camera.horizontalHeader().setVisible(True)
        self.tableWidget_search_camera.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_search_camera.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget_search_camera.horizontalHeader().setHighlightSections(True)
        self.tableWidget_search_camera.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_search_camera.verticalHeader().setVisible(False)
        self.tableWidget_search_camera.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_4.addWidget(self.tableWidget_search_camera)
        self.verticalLayout_3.addWidget(self.tb_frame)
        self.low_bot = QtWidgets.QFrame(self.see_frame)
        self.low_bot.setMinimumSize(QtCore.QSize(0, 20))
        self.low_bot.setObjectName("low_bot")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.low_bot)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.low_bot)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(150,150,150);\n"
"}")
        self.horizontalFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6.addWidget(self.horizontalFrame_2)
        self.resize_button = QtWidgets.QFrame(self.low_bot)
        self.resize_button.setMaximumSize(QtCore.QSize(20, 20))
        self.resize_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resize_button.setObjectName("resize_button")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.resize_button)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.resize_button)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/right_down.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.horizontalLayout_6.addWidget(self.resize_button)
        self.verticalLayout_3.addWidget(self.low_bot)
        self.horizontalLayout_3.addWidget(self.see_frame)
        self.verticalLayout_2.addWidget(self.verticalFrame_bot)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min_window.clicked['bool'].connect(MainWindow.showMinimized) # type: ignore
        self.pushButton_close_window.clicked['bool'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget_search_camera.setSortingEnabled(True)
        item = self.tableWidget_search_camera.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Модель камеры"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MAC"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IP-адрес"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Маска"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Прошивка"))
