# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: rgb(173,173,173);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame_top = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.horizontalFrame_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalFrame_top.setObjectName("horizontalFrame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame_top = QtWidgets.QFrame(self.horizontalFrame_top)
        self.verticalFrame_top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.verticalFrame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_top.setObjectName("verticalFrame_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.verticalFrame_top)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_top = QtWidgets.QLabel(self.verticalFrame_top)
        self.label_top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_top.setStyleSheet("QLabel {\n"
"background-color: rgb(173,173,173);\n"
"    spacing: 3px;           \n"
"    padding: 5px 10px;\n"
"    background-color: rgb(173,173,173);\n"
"    color: rgb(0,0,0);  \n"
"}\n"
"QLabel:pressed {\n"
"    border: 2px solid green;\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 5px;\n"
"}\n"
"QLabel:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.label_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_top.setText("")
        self.label_top.setObjectName("label_top")
        self.horizontalLayout_5.addWidget(self.label_top)
        self.horizontalLayout.addWidget(self.verticalFrame_top)
        self.frame_close = QtWidgets.QFrame(self.horizontalFrame_top)
        self.frame_close.setMaximumSize(QtCore.QSize(45, 45))
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_min_window = QtWidgets.QPushButton(self.frame_close)
        self.pushButton_min_window.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_min_window.setStyleSheet("QPushButton {\n"
"background-color: rgb(173,173,173);\n"
"    spacing: 3px;           \n"
"    padding: 5px 10px;\n"
"    background-color: rgb(173,173,173);\n"
"    color: rgb(0,0,0); \n"
"     border: 2px solid grey;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid green;\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_min_window.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_window.setIcon(icon)
        self.pushButton_min_window.setFlat(True)
        self.pushButton_min_window.setObjectName("pushButton_min_window")
        self.horizontalLayout_4.addWidget(self.pushButton_min_window)
        self.horizontalLayout.addWidget(self.frame_close)
        self.frame_min = QtWidgets.QFrame(self.horizontalFrame_top)
        self.frame_min.setMaximumSize(QtCore.QSize(45, 45))
        self.frame_min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_min.setObjectName("frame_min")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_min)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_close_window = QtWidgets.QPushButton(self.frame_min)
        self.pushButton_close_window.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_close_window.setStyleSheet("QPushButton {\n"
"background-color: rgb(173,173,173);\n"
"    spacing: 3px;           \n"
"    padding: 5px 10px;\n"
"    background-color: rgb(173,173,173);\n"
"    color: rgb(0,0,0);\n"
"    border: 2px solid grey;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 142, 119);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid green;\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.pushButton_close_window.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_window.setIcon(icon1)
        self.pushButton_close_window.setFlat(True)
        self.pushButton_close_window.setObjectName("pushButton_close_window")
        self.horizontalLayout_2.addWidget(self.pushButton_close_window)
        self.horizontalLayout.addWidget(self.frame_min)
        self.verticalLayout_2.addWidget(self.horizontalFrame_top)
        self.verticalFrame_bot = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_bot.setObjectName("verticalFrame_bot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame_bot)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_frame = QtWidgets.QFrame(self.verticalFrame_bot)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame.setObjectName("table_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.table_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_search_camera = QtWidgets.QTableWidget(self.table_frame)
        self.tableWidget_search_camera.setEnabled(True)
        self.tableWidget_search_camera.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget_search_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_search_camera.setStyleSheet("QTableWidget {\n"
"background-color: rgb(173,173,173);\n"
"    spacing: 3px;           \n"
"    padding: 5px 10px;\n"
"    background-color: rgb(173,173,173);\n"
"    color: rgb(0,0,0);  \n"
"    border: 2px solid grey;\n"
"}\n"
"QTableWidget:pressed {\n"
"    border: 2px solid green;\n"
"    background-color: rgb(85, 170, 127);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 5px;\n"
"}\n"
"QTableWidget:disabled {\n"
"    background-color: rgb(220,220,220,);\n"
"    color: rgb(150,150,150,);\n"
"}")
        self.tableWidget_search_camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_search_camera.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_search_camera.setWordWrap(False)
        self.tableWidget_search_camera.setCornerButtonEnabled(True)
        self.tableWidget_search_camera.setObjectName("tableWidget_search_camera")
        self.tableWidget_search_camera.setColumnCount(5)
        self.tableWidget_search_camera.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(203, 0, 0, 0))
        self.tableWidget_search_camera.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_camera.setHorizontalHeaderItem(4, item)
        self.tableWidget_search_camera.horizontalHeader().setVisible(True)
        self.tableWidget_search_camera.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_search_camera.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget_search_camera.horizontalHeader().setHighlightSections(True)
        self.tableWidget_search_camera.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_search_camera.verticalHeader().setVisible(False)
        self.tableWidget_search_camera.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.tableWidget_search_camera)
        self.low_bot = QtWidgets.QFrame(self.table_frame)
        self.low_bot.setMinimumSize(QtCore.QSize(0, 20))
        self.low_bot.setObjectName("low_bot")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.low_bot)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.low_bot)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6.addWidget(self.horizontalFrame_2)
        self.resize_button = QtWidgets.QFrame(self.low_bot)
        self.resize_button.setMaximumSize(QtCore.QSize(20, 20))
        self.resize_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resize_button.setObjectName("resize_button")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.resize_button)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6.addWidget(self.resize_button)
        self.verticalLayout_3.addWidget(self.low_bot)
        self.verticalLayout.addWidget(self.table_frame)
        self.verticalLayout_2.addWidget(self.verticalFrame_bot)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min_window.clicked['bool'].connect(MainWindow.showMinimized) # type: ignore
        self.pushButton_close_window.clicked['bool'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget_search_camera.setSortingEnabled(True)
        item = self.tableWidget_search_camera.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Модель камеры"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MAC"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IP-адрес"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Маска"))
        item = self.tableWidget_search_camera.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Прошивка"))
